language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    on_success: always
    on_failure: always
node_js:
  - '8'
  - '6'
before_script:
  - npm prune -d
script:
  - npm run build -d
after_success:
  - npm run release -d
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
