language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email:
    on_success: always
    on_failure: always
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
