language: node_js
cache:
	directories:
		- ~/.npm
notifications:
	email: true
node_js:
	- '8'
	- '6'
	- '4'
before_script:
	- npm prune
script:
	- npm run build
after_success:
	- npm run semantic-release
branches:
	except:
		- /^v\d+\.\d+\.\d+$/
